# Generated by Django 5.0.3 on 2024-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('adminId', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
