# Generated by Django 5.0.3 on 2024-03-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminCredentials',
            new_name='UserCredentials',
        ),
        migrations.RenameField(
            model_name='usercredentials',
            old_name='adminId',
            new_name='applicationID',
        ),
    ]
