# Generated by Django 5.0.3 on 2024-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0002_rename_admincredentials_usercredentials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredentials',
            old_name='applicationID',
            new_name='application_id',
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='course_applied',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
