# Generated by Django 5.0.3 on 2024-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0003_rename_applicationid_usercredentials_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
