# Generated by Django 5.0.3 on 2024-03-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0005_addresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresult',
            name='figuralReasoning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addresult',
            name='qualitativeReasoning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addresult',
            name='verbalComprehension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addresult',
            name='verbalReasoning',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
