# Generated by Django 5.0.3 on 2024-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0006_alter_addresult_figuralreasoning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresult',
            name='figuralReasoning',
        ),
        migrations.RemoveField(
            model_name='addresult',
            name='qualitativeReasoning',
        ),
        migrations.RemoveField(
            model_name='addresult',
            name='verbalComprehension',
        ),
        migrations.RemoveField(
            model_name='addresult',
            name='verbalReasoning',
        ),
        migrations.AddField(
            model_name='addresult',
            name='figural_Reasoning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addresult',
            name='qualitative_Reasoning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addresult',
            name='verbal_Comprehension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addresult',
            name='verbal_Reasoning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
