# Generated by Django 5.0.3 on 2024-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0007_remove_addresult_figuralreasoning_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredentials',
            old_name='application_id',
            new_name='application_idU',
        ),
        migrations.AddField(
            model_name='addresult',
            name='application_idR',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addresult',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addresult',
            name='figural_Reasoning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addresult',
            name='qualitative_Reasoning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addresult',
            name='verbal_Comprehension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addresult',
            name='verbal_Reasoning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
