# Generated by Django 5.0.3 on 2024-03-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0009_addresult_vscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresult',
            name='vscore',
        ),
    ]
